apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-demo
  labels:
    app: go-api-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api-demo
  template:
    metadata:
      labels:
        app: go-api-demo
    spec:
      containers:
      - name: go-api-demo
        image: lcostea/go-api-demo:0.1.0
        volumeMounts:
        - name: synced
          mountPath: /config
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.0.1
        volumeMounts:
        - name: synced
          mountPath: /tmp/git
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/kubernetes/git-sync.git
        - name: GIT_SYNC_DEST
          value: git-sync
      volumes:
      - name: synced
        emptyDir: {}
