apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-demo-checks
  labels:
    app: go-api-demo-checks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-api-demo-checks
  template:
    metadata:
      labels:
        app: go-api-demo-checks
    spec:
      containers:
      - name: go-api-demo
        image: lcostea/go-api-demo:0.1.0
        livenessProbe:
          httpGet:
            path: /healthy
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          #timeoutSeconds: 2

